spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:54321/postgres
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # For development; consider 'validate' or migrations for production
    show-sql: true

server:
  port: 8080

cors:
  allowed-origins:
    - "http://localhost:8000"

kafka:
  group-id: training-service
  topics:
    user-creation: user-creation

logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace